// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortfolioApi.Data;

#nullable disable

namespace PortfolioAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260705194618_AddCertificateLink")]
    partial class AddCertificateLink
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("PortfolioApi.Models.Certificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Organization")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleTr")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Certificates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = "Ağustos 2025",
                            ImageUrl = "/certificates/udemy-webdev.jpg",
                            Link = "https://ude.my/UC-9e7ed3ba-3935-47ae-9c4a-3771f959fb4d",
                            Organization = "Udemy — Levent Ertunalılar",
                            TitleEn = "From Zero to Advanced Web Development (HTML, CSS, Javascript)",
                            TitleTr = "Sıfırdan İleri Düzey Web Geliştirme (HTML, CSS, Javascript)"
                        });
                });

            modelBuilder.Entity("PortfolioApi.Models.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateSent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("PortfolioApi.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DemoUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionTr")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GitHubUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Technologies")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleTr")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DemoUrl = "#",
                            DescriptionEn = "Modern and fast online store solution.",
                            DescriptionTr = "Modern ve hızlı online mağaza çözümü.",
                            GitHubUrl = "#",
                            ImageUrl = "",
                            Technologies = "React, Node.js, Stripe",
                            TitleEn = "E-Commerce Platform",
                            TitleTr = "E-Ticaret Platformu"
                        },
                        new
                        {
                            Id = 2,
                            DemoUrl = "#",
                            DescriptionEn = "Personal productivity and organization tool.",
                            DescriptionTr = "Kişisel verimlilik ve organizasyon aracı.",
                            GitHubUrl = "#",
                            ImageUrl = "",
                            Technologies = "React, Firebase, CSS",
                            TitleEn = "Task Manager App",
                            TitleTr = "Görev Yöneticisi"
                        },
                        new
                        {
                            Id = 3,
                            DemoUrl = "#",
                            DescriptionEn = "Customizable portfolio for developers.",
                            DescriptionTr = "Geliştiriciler için özelleştirilebilir portfolyo.",
                            GitHubUrl = "#",
                            ImageUrl = "",
                            Technologies = "JavaScript, HTML, CSS",
                            TitleEn = "Portfolio Website",
                            TitleTr = "Portfolyo Sitesi"
                        });
                });

            modelBuilder.Entity("PortfolioApi.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "frontend",
                            Color = "#61DAFB",
                            Name = "React"
                        },
                        new
                        {
                            Id = 2,
                            Category = "frontend",
                            Color = "#F7DF1E",
                            Name = "JavaScript"
                        },
                        new
                        {
                            Id = 3,
                            Category = "frontend",
                            Color = "#E34F26",
                            Name = "HTML5"
                        },
                        new
                        {
                            Id = 4,
                            Category = "frontend",
                            Color = "#1572B6",
                            Name = "CSS3"
                        },
                        new
                        {
                            Id = 5,
                            Category = "frontend",
                            Color = "#38B2AC",
                            Name = "Tailwind"
                        },
                        new
                        {
                            Id = 6,
                            Category = "backend",
                            Color = "#777BB4",
                            Name = "PHP"
                        },
                        new
                        {
                            Id = 7,
                            Category = "backend",
                            Color = "#EF4223",
                            Name = "CodeIgniter"
                        },
                        new
                        {
                            Id = 8,
                            Category = "backend",
                            Color = "#4479A1",
                            Name = "MySQL"
                        },
                        new
                        {
                            Id = 9,
                            Category = "backend",
                            Color = "#512BD4",
                            Name = "ASP.NET Core"
                        },
                        new
                        {
                            Id = 10,
                            Category = "tools",
                            Color = "#F05032",
                            Name = "Git"
                        },
                        new
                        {
                            Id = 11,
                            Category = "tools",
                            Color = "#181717",
                            Name = "GitHub"
                        },
                        new
                        {
                            Id = 12,
                            Category = "tools",
                            Color = "#F24E1E",
                            Name = "Figma"
                        },
                        new
                        {
                            Id = 13,
                            Category = "tools",
                            Color = "#007ACC",
                            Name = "VS Code"
                        },
                        new
                        {
                            Id = 14,
                            Category = "ai",
                            Color = "#10A37F",
                            Name = "ChatGPT-4o"
                        },
                        new
                        {
                            Id = 15,
                            Category = "ai",
                            Color = "#8E75FF",
                            Name = "Gemini"
                        },
                        new
                        {
                            Id = 16,
                            Category = "ai",
                            Color = "#D97757",
                            Name = "Claude"
                        },
                        new
                        {
                            Id = 17,
                            Category = "ai",
                            Color = "#2B2B2B",
                            Name = "Cursor"
                        },
                        new
                        {
                            Id = 18,
                            Category = "ai",
                            Color = "#FF3366",
                            Name = "CodeFormer"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
